# Generated by Django 3.0 on 2020-01-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Medical',
        ),
        migrations.DeleteModel(
            name='Organ',
        ),
        migrations.DeleteModel(
            name='PostCat',
        ),
        migrations.DeleteModel(
            name='PostPost',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
