# Generated by Django 3.0 on 2019-12-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191227_0651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Cat',
        ),
    ]
